services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cicd
      POSTGRES_PASSWORD: cicd
      POSTGRES_DB: cicd
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data    
  
  api:
    build: ./apps/api
    container_name: cicd_api
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pg_data: